#workflows
name: Hello

on:
  workflow_dispatch

 
#jobs
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name:Say hello to everyone
        run: echo "Hello Dosto"
      
#Steps

#Actions
