name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Cloning the code"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build the code
        run: echo "Building the code"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test the code
        run: echo "Testing the code"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the code
        run: echo "Deploying the code"
