name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest
    steps:
    #this will automatically clone the code
    - name: clone the code
      uses: actions/checkout@v4

#install teh linter tool
    - name: Install Linter
      run: pip install ruff

# This step will run teh linter
    - name: Check the files for linting
      run: ruff check .
